# Section A: Data Structures & Control Structures

1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [38]:
list1=[11,22,33,44,55]


In [39]:
#APPEND FUNCTION
list1.append(66)
list1

[11, 22, 33, 44, 55, 66]

In [40]:
#EXTEND FUNCTION
list1.extend([77,88])
list1

[11, 22, 33, 44, 55, 66, 77, 88]

In [41]:
#INSERT FUNCTION
list1.insert(0,0)
list1

[0, 11, 22, 33, 44, 55, 66, 77, 88]

In [43]:
#REMOVE FUNCTION
list1.remove(11)
list1

[0, 22, 33, 44, 55, 66, 77, 88]

In [44]:
#POP FUNCTION
list1.pop(3)
list1

[0, 22, 33, 55, 66, 77, 88]

In [35]:
#CLEAR FUNCTION
list1.clear()
list1

[]

In [47]:
#INDEX FUNCTION
list1.index(22)


1

In [49]:
#COUNT FUNCTION
list1.count(22)

1

In [54]:
#SORT FUNCTION
list1.sort(reverse=True)
list1

[88, 77, 66, 55, 33, 22, 0]

In [56]:
#REVERSE FUNCTION
list1.reverse()
list1

[88, 77, 66, 55, 33, 22, 0]

2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [60]:
Tuple=("Anoop","Mohan","Neeraj")
Tuple[1]="Mohanty"
Tuple
# ANSWER:- The value inside the tuple didnt changed because tuples are immutable if you want to change anything in future try using list beacause it is mutable

TypeError: 'tuple' object does not support item assignment

3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [64]:
set1={1,1,2,2,3,3,4,5,3}
set1
#ANSWER:- In Set the duplicates values get removes thus remaining with unique values so if we want to make a list were we dont want to have duplicate values we can use sets


{1, 2, 3, 4, 5}

4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [69]:
dict1={"Name":"Anoop","age":23,"city":"Hyderabad"}
dict1["email"]=dict1.pop("age")
dict1

{'Name': 'Anoop', 'city': 'Hyderabad', 'email': 23}

5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [70]:
age=int(input("Enter Your Age"))
if (age>=18):
  print("YOU ARE ELIGIBLE FOR VOTING")
else:
  print("YOU ARE NOT ELIGIBLE FOR VOTING")

Enter Your Age24
YOU ARE ELIGIBLE FOR VOTING


6. Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [76]:
marks=int(input("Enter Your Marks"))
if (marks>=90):
  print("'A'")
elif(marks<=89&marks>=75):
  print("'B'")
elif(marks<=74&marks>=50):
  print("'C'")
elif(marks<50):
  print("FAIL")
else:
  print("INVALID INPUT")

Enter Your Marks88
'B'


7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [78]:
num=int(input("Enter A Number"))
if(num==0):
  print("Its a Zero")
elif(num>0):
  print("Its a positive number")
else:
  print("Its a negative number")

Enter A Number-44
Its a negative number


# Section B: Numpy

8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [79]:
import numpy as np

In [82]:
scalar=np.array(5)
print(scalar)

5


In [84]:
_1d = np.array([1, 2, 3, 4, 5])
print(_1d)

[1 2 3 4 5]


In [86]:
_2d=np.array([[1,2,3],[4,5,6]])
print(_2d)

[[1 2 3]
 [4 5 6]]


9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [89]:
rand_array=np.random.randint(0, 100,size=(4,4))
print(rand_array)

[[95 66 21 29]
 [88 46 92 52]
 [78 86 77 44]
 [61 98 59 20]]


10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [90]:
import pandas as pd
arr=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
df=pd.DataFrame(arr,columns=['A','B','C'])
df

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

# Section C: Exploring Pandas
11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [91]:
data={
    'Name': ['Anoop', 'Bobby', 'mohan', 'neeraj', 'raj', 'shukla', 'mahananda', 'ram', 'sita', 'raju'],
    'Age': [25, 30, 35, 40, 28, 50, 45, 33, 29, 25],
    'City': ['Delhi', 'Mumbai', 'Kolkata', 'Chennai', 'Delhi', 'Mumbai', 'Chennai', 'Kolkata', 'Delhi', 'Delhi'],
    'Salary': [50000, 60000, 40000, 70000, 52000, np.nan, 66000, 62000, 58000, 50000]
}
df = pd.DataFrame(data)
print(df.info())
print(df.describe())

# Select 'Name' and 'City' columns
name_city = df[['Name', 'City']]
print(name_city)

# Drop 'City' column
df_dropped = df.drop('City', axis=1)
print(df_dropped)

# Fill missing 'Salary' values with the mean of Salary column
salary_mean = df['Salary'].mean()
df['Salary'].fillna(salary_mean, inplace=True)
print(df)

# Remove duplicate rows
df_no_duplicates = df.drop_duplicates()
print(df_no_duplicates)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None
             Age        Salary
count  10.000000      9.000000
mean   34.000000  56444.444444
std     8.524475   9315.459075
min    25.000000  40000.000000
25%    28.250000  50000.000000
50%    31.500000  58000.000000
75%    38.750000  62000.000000
max    50.000000  70000.000000
        Name     City
0      Anoop    Delhi
1      Bobby   Mumbai
2      mohan  Kolkata
3     neeraj  Chennai
4        raj    Delhi
5     shukla   Mumbai
6  mahananda  Chennai
7        ram  Kolkata
8       sita    Delhi
9       raju    Delhi
        Name  Age   Salary
0      Anoop   25  50000.0
1      Bobby   30  60000.0
2  

/tmp/ipython-input-1761291012.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(salary_mean, inplace=True)
